/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateCompletionRequestPrompt
 */
public class CreateCompletionRequestPromptTest {
    private final CreateCompletionRequestPrompt model = new CreateCompletionRequestPrompt();

    /**
     * Model tests for CreateCompletionRequestPrompt
     */
    @Test
    public void testCreateCompletionRequestPrompt() {
        // TODO: test CreateCompletionRequestPrompt
    }

}
