/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.AssistantToolsCode;
import org.openapitools.client.model.AssistantToolsFunction;
import org.openapitools.client.model.AssistantToolsRetrieval;
import org.openapitools.client.model.FunctionObject;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateThreadAndRunRequestToolsInner
 */
public class CreateThreadAndRunRequestToolsInnerTest {
    private final CreateThreadAndRunRequestToolsInner model = new CreateThreadAndRunRequestToolsInner();

    /**
     * Model tests for CreateThreadAndRunRequestToolsInner
     */
    @Test
    public void testCreateThreadAndRunRequestToolsInner() {
        // TODO: test CreateThreadAndRunRequestToolsInner
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'function'
     */
    @Test
    public void functionTest() {
        // TODO: test function
    }

}
