/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.MessageContentTextAnnotationsFileCitationObject;
import org.openapitools.client.model.MessageContentTextAnnotationsFileCitationObjectFileCitation;
import org.openapitools.client.model.MessageContentTextAnnotationsFilePathObject;
import org.openapitools.client.model.MessageContentTextAnnotationsFilePathObjectFilePath;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MessageContentTextObjectTextAnnotationsInner
 */
public class MessageContentTextObjectTextAnnotationsInnerTest {
    private final MessageContentTextObjectTextAnnotationsInner model = new MessageContentTextObjectTextAnnotationsInner();

    /**
     * Model tests for MessageContentTextObjectTextAnnotationsInner
     */
    @Test
    public void testMessageContentTextObjectTextAnnotationsInner() {
        // TODO: test MessageContentTextObjectTextAnnotationsInner
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'text'
     */
    @Test
    public void textTest() {
        // TODO: test text
    }

    /**
     * Test the property 'fileCitation'
     */
    @Test
    public void fileCitationTest() {
        // TODO: test fileCitation
    }

    /**
     * Test the property 'startIndex'
     */
    @Test
    public void startIndexTest() {
        // TODO: test startIndex
    }

    /**
     * Test the property 'endIndex'
     */
    @Test
    public void endIndexTest() {
        // TODO: test endIndex
    }

    /**
     * Test the property 'filePath'
     */
    @Test
    public void filePathTest() {
        // TODO: test filePath
    }

}
