/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.ainoya.client.model;

import com.github.ainoya.client.model.ChatCompletionMessageToolCall;
import com.github.ainoya.client.model.ChatCompletionRequestAssistantMessageFunctionCall;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ChatCompletionRequestAssistantMessage
 */
public class ChatCompletionRequestAssistantMessageTest {
    private final ChatCompletionRequestAssistantMessage model = new ChatCompletionRequestAssistantMessage();

    /**
     * Model tests for ChatCompletionRequestAssistantMessage
     */
    @Test
    public void testChatCompletionRequestAssistantMessage() {
        // TODO: test ChatCompletionRequestAssistantMessage
    }

    /**
     * Test the property 'content'
     */
    @Test
    public void contentTest() {
        // TODO: test content
    }

    /**
     * Test the property 'role'
     */
    @Test
    public void roleTest() {
        // TODO: test role
    }

    /**
     * Test the property 'toolCalls'
     */
    @Test
    public void toolCallsTest() {
        // TODO: test toolCalls
    }

    /**
     * Test the property 'functionCall'
     */
    @Test
    public void functionCallTest() {
        // TODO: test functionCall
    }

}
