/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.ainoya.client.model;

import com.github.ainoya.client.model.MessageDeltaContentTextAnnotationsFileCitationObject;
import com.github.ainoya.client.model.MessageDeltaContentTextAnnotationsFileCitationObjectFileCitation;
import com.github.ainoya.client.model.MessageDeltaContentTextAnnotationsFilePathObject;
import com.github.ainoya.client.model.MessageDeltaContentTextAnnotationsFilePathObjectFilePath;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MessageDeltaContentTextObjectTextAnnotationsInner
 */
public class MessageDeltaContentTextObjectTextAnnotationsInnerTest {
    private final MessageDeltaContentTextObjectTextAnnotationsInner model = new MessageDeltaContentTextObjectTextAnnotationsInner();

    /**
     * Model tests for MessageDeltaContentTextObjectTextAnnotationsInner
     */
    @Test
    public void testMessageDeltaContentTextObjectTextAnnotationsInner() {
        // TODO: test MessageDeltaContentTextObjectTextAnnotationsInner
    }

    /**
     * Test the property 'index'
     */
    @Test
    public void indexTest() {
        // TODO: test index
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'text'
     */
    @Test
    public void textTest() {
        // TODO: test text
    }

    /**
     * Test the property 'fileCitation'
     */
    @Test
    public void fileCitationTest() {
        // TODO: test fileCitation
    }

    /**
     * Test the property 'startIndex'
     */
    @Test
    public void startIndexTest() {
        // TODO: test startIndex
    }

    /**
     * Test the property 'endIndex'
     */
    @Test
    public void endIndexTest() {
        // TODO: test endIndex
    }

    /**
     * Test the property 'filePath'
     */
    @Test
    public void filePathTest() {
        // TODO: test filePath
    }

}
