/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.ainoya.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RealtimeClientEventSessionUpdateSessionInputAudioTranscription
 */
public class RealtimeClientEventSessionUpdateSessionInputAudioTranscriptionTest {
    private final RealtimeClientEventSessionUpdateSessionInputAudioTranscription model = new RealtimeClientEventSessionUpdateSessionInputAudioTranscription();

    /**
     * Model tests for RealtimeClientEventSessionUpdateSessionInputAudioTranscription
     */
    @Test
    public void testRealtimeClientEventSessionUpdateSessionInputAudioTranscription() {
        // TODO: test RealtimeClientEventSessionUpdateSessionInputAudioTranscription
    }

    /**
     * Test the property 'model'
     */
    @Test
    public void modelTest() {
        // TODO: test model
    }

}
