/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.ainoya.openai.client.api;

import dev.ainoya.client.ApiException;
import dev.ainoya.client.model.AssistantObject;
import dev.ainoya.client.model.ModifyAssistantRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AssistantApi
 */
@Disabled
public class AssistantApiTest {

    private final AssistantApi api = new AssistantApi();

    /**
     * Modifies an assistant.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void modifyAssistantTest() throws ApiException {
        String assistantId = null;
        ModifyAssistantRequest modifyAssistantRequest = null;
        AssistantObject response = api.modifyAssistant(assistantId, modifyAssistantRequest);
        // TODO: test validations
    }

}
